apiVersion: v1
kind: Secret
metadata:
  name: onapwebsocclisecret
type: Opaque
data:
  HOST: MTAuMTMzLjk4LjExNQo=
  USER_NAME: YWRtaW4K
  PASSWORD: YWRtaW5wdwo=
  ONAP_HOST: MTAuMC4xMTcuMjIK
  PORT: MzAyMjcK
  TOPIC: dW5hdXRoZW50aWNhdGVkLlNFQ19GQVVMVF9PVVRQVVQK
